VERSION = "1.0"

SAVE_FOLDER = "saved"
DEFAULT_COLLECTION_NAME = "Default"

DEFAULT_PADDING = 10

TEXT_LINE_HEIGHT = 5

IMAGE_EXTENSION = ".png"
IMAGE_EXTENSION_TYPE = "PNG"

TEXT_FILE_NAME = "TEXTS.txt"

# Between each entry
TEXT_MARKER = "\n§█§\n"
# Between image names
TEXT_IMAGE_SEPARATOR = ", "
# Between images and text
TEXT_SEPARATOR = "\n"


BANNER_BACKGROUND_COLOR = "#AAAAAA"

MAX_PREVIEW_IMAGE_SIZE = 100